### PR TITLE
Switch to external qrcode library and don't write to the filesystem

### PR DESCRIPTION
**Pull request by samwilson**
Remove the phpqrcode library and replace it with endroid/qr-code,
loading the new one with Composer.

This removes the need to write the qrcode files to the filesytem,
which simplifies the code and removes an attack vector.

### CODE REVIEW

**Comment by samwilson** [comment]
This may need some discussion! :-) This PR is just me suggesting an idea.

One thing I'm not sure about is how to translate the old library's idea of the `size` parameter to the new library's. I've added a factor of 30, but this is arbitrary. It sort of looks about right to me, but maybe others have different ideas?

My main motivation for this is to not have to give the web server user write access to the filesystem. It also looks like the phpqrcode library is abandoned, so it's good to use something that's actively maintained.

**Comment by samwilson** [comment]
This also fixes a bug with syntax such as `{{#qrlite:foo"bar;>foo<bar}}`

**Comment by samwilson** [comment]
@gesinn-it @Fannon do either of you have a moment to review this? Thanks!

**Comment by Fannon** [comment]
Hi @samwilson 

thanks for the PR!
Currently I don't have a setup to really test this extension, but in general: The changes you propose definately make sense.

I see two potentials issues:
* Now we have a hard dependency on composer. If I remember correctly, the reason why the qr lib was put into the extension directly was to avoid this. But that was at a time when composer support was still spotty in the MW ecosystem.
* Did you think of potential error handling? I'm not familiar with the new library - but if there's a chance that errors happen, we should keep the error response / handling in place. The previous behavior was that instead of crashing in PHP, we returned a `<span class="error-message">`.

**Comment by samwilson** [comment]
@Fannon sorry for my very slow reply! This slipped through the net.

I think the dependency on Composer is acceptable these days. There are lots of extensions that install dependencies like this, and Composer has become a required part of MediaWiki.

Great point about the error handling, I've changed the patch to leave in the Exception catching. There's also the error that happens when the composer library isn't installed, so I've also added a check for that.

**Comment by samwilson** [comment]
Oops, I also need to upgrade `endroid/qr-code` to [4.6](https://packagist.org/packages/endroid/qr-code#4.6.1). Doing that now.

**Comment by samwilson** [comment]
Okay, this is ready for review again now. Thanks!

**Comment by samwilson** [comment]
I spoke too soon: #8 needs to be merged before this one.

**Comment by gesinn-it-gea** [comment]
Thanks for your PR (and sorry for the late feedback)! We'll have a look and come back to you. Not writing to the file system and using a maintained lib are definitely good things!

**Comment by gesinn-it-gea** [comment]
@samwilson ... sounds good. We are enhancing the CI this week a little bit so that QRLite is in a good shape again.

**Pull request merged**
