### PR TITLE
Switch to HookHandlers system

### PR DESCRIPTION
**Pull request by samwilson**
This moves the PHP classes to their own directory, and switches to using the new HookHandlers system for using hooks.

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
@samwilson ... again many thanks for your contribution! Shall we merge this PR already or do you want to add something?

**Comment by samwilson** [comment]
Oh, good point: I need to add [requires](https://www.mediawiki.org/wiki/Manual:Extension.json/Schema#requires) 1.35, for [HookHandlers](https://www.mediawiki.org/wiki/Manual:Extension.json/Schema#HookHandlers) support. Will in the morning! :)

**Comment by samwilson** [comment]
Okay, this is ready for review now. Thanks!

**Comment by gesinn-it-gea** [comment]
mhh, `make ci` says:

```
> phpcs -p -s
....EEE. 8 / 8 (100%)



FILE: /var/www/html/extensions/QRLite/src/QRLite.functions.php
----------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 22 | WARNING | Duplicate class name
    |         | "MediaWiki\Extension\QrLite\QRLiteFunctions" found;
    |         | first defined in
    |         | /var/www/html/extensions/QRLite/src/QRLiteFunctions.php
    |         | on line 24
    |         | (Generic.Classes.DuplicateClassName.Found)
 22 | ERROR   | Class name 'QRLiteFunctions' does not match filename
    |         | 'QRLite.functions.php'
    |         | (MediaWiki.Files.ClassMatchesFilename.NotMatch)
----------------------------------------------------------------------


FILE: /var/www/html/extensions/QRLite/QRLite.hooks.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 9 | ERROR | Class name 'QRLiteHooks' does not match filename
   |       | 'QRLite.hooks.php'
   |       | (MediaWiki.Files.ClassMatchesFilename.NotMatch)
----------------------------------------------------------------------


FILE: /var/www/html/extensions/QRLite/QRLite.functions.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 20 | ERROR | Class name 'QRLiteFunctions' does not match filename
    |       | 'QRLite.functions.php'
    |       | (MediaWiki.Files.ClassMatchesFilename.NotMatch)
----------------------------------------------------------------------

Time: 2.01 secs; Memory: 8MB

```

**Comment by gesinn-it-gea** [comment]
... this is probably not shown in the PR CI runs since your recent commits are not in yet.

**Comment by samwilson** [comment]
That's a strange error. I'm not able to reproduce it; for me, phpcs runs without error. Those files have been renamed in this patch, and `src/QRLite.functions.php` has _never_ existed. It sort of seems like the git checkout has stopped halfway through or something weird, or maybe it's about how Docker copies the files around.

> since your recent commits are not in yet.

I'm not sure you mean. I think this patch is on top of current master, and it contains only one commit.

**Comment by gesinn-it-gea** [comment]
uuh, sorry. I had a messed up working directory. All looks great!

**Pull request merged**
