### PR TITLE
Add npm test script for various linting etc.

### PR DESCRIPTION
**Pull request by samwilson**
This follows the MediaWiki conventions for these sorts of tests.

### CODE REVIEW

**Comment by samwilson** [comment]
If you [hide whitespace](https://github.com/gesinn-it/QRLite/pull/12/files?diff=unified&w=1) you can get a better idea of the actual changes here. Mostly it's line endings and indents.

**Comment by samwilson** [comment]
I wasn't sure how this should be added to the Makefile (and so CI).

**Comment by gesinn-it-gea** [comment]
`make ci` at the calls `composer test` https://github.com/gesinn-it/QRLite/blob/master/Makefile#L36

**Comment by samwilson** [comment]
I've added a separate `npm-test` target (is that what they're called? I'm afraid it's probably been ten years since I touched a Makefile!).

Where should the `npm ci` command be added though? And does the docker image even include npm?

**Comment by gesinn-it-gea** [comment]
I'll have a look...

**Comment by gesinn-it-gea** [comment]
Here's a more complex example of such a Dockerfile: https://github.com/SemanticMediaWiki/SemanticDrilldown/blob/master/Dockerfile

**Comment by samwilson** [comment]
Okay great, I think I've sorted it all out now. See what you think.

**Comment by gesinn-it-gea** [comment]
Many thanks for your contribution!

**Pull request merged**
